version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: hopla_prueba
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - mynetwork

volumes:
  pgdata:
networks:
  mynetwork: