# Generated by Django 5.0.4 on 2024-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticket_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='images_count',
            field=models.IntegerField(default=1),
        ),
    ]
